import type { Locale } from "@/lib/i18n/locale";

export type TeetherCategory = "frutas" | "silicone" | "pao" | "frio" | "extras";

export const TEETHER_CATEGORY_LABEL: Record<TeetherCategory, string> = {
  frutas: "Frutas",
  silicone: "Silicone",
  pao: "Pão & biscoito",
  frio: "Frio",
  extras: "Extras",
};

export const TEETHER_CATEGORY_LABEL_ES: Record<TeetherCategory, string> = {
  frutas: "Frutas",
  silicone: "Silicona",
  pao: "Pan y galletas",
  frio: "Frío",
  extras: "Extras",
};

export function getTeetherCategoryLabel(locale: Locale = "pt-BR"): Record<TeetherCategory, string> {
  return locale === "es" ? TEETHER_CATEGORY_LABEL_ES : TEETHER_CATEGORY_LABEL;
}

export interface Teether {
  id: string;
  name: string;
  emoji: string;
  category: TeetherCategory;
  minAgeMonths: number;
  temperature: string;
  prep: string;
  maxDurationMinutes: number;
  safety: string;
  benefits: string;
  howToOffer: string;
  goodForActiveTeething: boolean;
}

export const TEETHERS: Teether[] = [
  {
    id: "maca",
    name: "Maçã",
    emoji: "🍎",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Corte um bastão grosso com casca, gelado na geladeira por 30 minutos.",
    maxDurationMinutes: 10,
    safety: "Supervisione sempre — pedaços podem se soltar com a mordida. Retire se ficar pequeno demais para segurar com firmeza.",
    benefits: "O frio ajuda a aliviar a inflamação da gengiva; a casca dá resistência para morder sem quebrar fácil.",
    howToOffer: "Segure a outra ponta nos primeiros usos, até o bebê pegar o jeito de segurar sozinho.",
    goodForActiveTeething: true,
  },
  {
    id: "cenoura",
    name: "Cenoura",
    emoji: "🥕",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use um bastão inteiro e grosso, gelado na geladeira — nunca cozida (fica mole demais e quebra).",
    maxDurationMinutes: 10,
    safety: "Use sempre um bastão grande demais para caber inteiro na boca. Descarte assim que aparecerem marcas fundas de mordida.",
    benefits: "Textura firme e fria, ótima para massagear a gengiva.",
    howToOffer: "Ofereça pela ponta mais grossa, seguindo o cabo com a mão.",
    goodForActiveTeething: true,
  },
  {
    id: "banana-congelada",
    name: "Banana congelada",
    emoji: "🍌",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Congelada",
    prep: "Congele meia banana com casca por 1 a 2 horas, até ficar firme mas não pedra.",
    maxDurationMinutes: 10,
    safety: "Fica mole rápido — troque assim que amolecer demais e vire papinha, para evitar sufoco.",
    benefits: "O frio intenso é um dos mais eficazes para alívio imediato da dor.",
    howToOffer: "Ofereça com a casca como apoio para a mão do bebê.",
    goodForActiveTeething: true,
  },
  {
    id: "melancia",
    name: "Melancia",
    emoji: "🍉",
    category: "frutas",
    minAgeMonths: 8,
    temperature: "Gelada (geladeira)",
    prep: "Corte um bastão grosso sem sementes, gelado.",
    maxDurationMinutes: 10,
    safety: "Retire todas as sementes antes de oferecer. Fica escorregadia — supervisione de perto.",
    benefits: "Refrescante e hidratante, ótima em dias quentes de teething.",
    howToOffer: "Ofereça em pedaço grande o suficiente para não caber inteiro na boca.",
    goodForActiveTeething: true,
  },
  {
    id: "pera",
    name: "Pera",
    emoji: "🍐",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use uma pera firme (não muito madura), em bastão grosso, gelada.",
    maxDurationMinutes: 10,
    safety: "Peras muito maduras amolecem rápido e quebram — prefira peras mais firmes para essa finalidade.",
    benefits: "Textura firme e levemente doce, bem aceita pela maioria dos bebês.",
    howToOffer: "Ofereça pela ponta, segurando junto nos primeiros usos.",
    goodForActiveTeething: true,
  },
  {
    id: "beterraba",
    name: "Beterraba",
    emoji: "🟣",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use um bastão grosso cru, gelado — a textura bem firme é o que funciona aqui.",
    maxDurationMinutes: 10,
    safety: "Pode manchar roupas e pele temporariamente (é só a cor, inofensivo). Supervisione como qualquer mordedor de vegetal cru.",
    benefits: "Muito firme e resistente, dura mais tempo sem quebrar do que outros vegetais.",
    howToOffer: "Ofereça pela ponta mais fina, mantendo a parte grossa fora da boca.",
    goodForActiveTeething: true,
  },
  {
    id: "mordedor-silicone",
    name: "Mordedor de silicone",
    emoji: "🧸",
    category: "silicone",
    minAgeMonths: 3,
    temperature: "Ambiente ou gelado (próprio para geladeira)",
    prep: "Escolha um mordedor de silicone alimentício (grade INMETRO/FDA), sem BPA, com peça única — sem partes pequenas que possam soltar.",
    maxDurationMinutes: 30,
    safety: "Verifique rachaduras antes de cada uso e substitua ao primeiro sinal de desgaste. Nunca amarre no pescoço do bebê.",
    benefits: "Pode ser gelado na geladeira (nunca no freezer, a maioria racha), reutilizável e desenhado para segurança.",
    howToOffer: "Lave após cada uso e mantenha limpo entre uma oferta e outra.",
    goodForActiveTeething: true,
  },
  {
    id: "pao",
    name: "Pão",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente ou levemente torrado",
    prep: "Use uma casca grossa de pão francês ou uma fatia de pão integral levemente torrada, em tira comprida.",
    maxDurationMinutes: 10,
    safety: "Fica mole com a saliva — troque quando começar a desmanchar, para não virar risco de engasgo.",
    benefits: "Textura firme no início, vai amolecendo aos poucos conforme o bebê mastiga.",
    howToOffer: "Ofereça pela ponta, deixando a outra parte de fora da boca.",
    goodForActiveTeething: false,
  },
  {
    id: "biscoito-polvilho",
    name: "Biscoito de polvilho",
    emoji: "🥨",
    category: "pao",
    minAgeMonths: 8,
    temperature: "Ambiente",
    prep: "Escolha um biscoito de polvilho simples, sem açúcar e sem recheio, em formato de argola ou bastão.",
    maxDurationMinutes: 10,
    safety: "Amolece e pode quebrar em pedaços — supervisione e retire pedaços pequenos que se soltarem.",
    benefits: "Crocante no início, prático para levar na bolsa.",
    howToOffer: "Ofereça inteiro, segurando pela borda até o bebê pegar sozinho.",
    goodForActiveTeething: false,
  },
  {
    id: "torrada",
    name: "Torrada",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente",
    prep: "Torre uma fatia de pão integral até ficar bem firme e corte em tiras compridas.",
    maxDurationMinutes: 10,
    safety: "Amolece rápido com a saliva — troque quando ficar mole.",
    benefits: "Mais firme que o pão comum, dura um pouco mais na mordida.",
    howToOffer: "Ofereça em tiras compridas, fáceis de segurar.",
    goodForActiveTeething: false,
  },
  {
    id: "pano-congelado",
    name: "Pano de algodão congelado",
    emoji: "🧊",
    category: "frio",
    minAgeMonths: 3,
    temperature: "Congelado",
    prep: "Molhe um pano de algodão limpo em água filtrada, torça, dobre e congele por 30-40 minutos.",
    maxDurationMinutes: 15,
    safety: "Verifique que não está tão duro a ponto de machucar a gengiva — o pano deve ceder um pouco à pressão.",
    benefits: "Alívio frio profundo, sem risco de soltar pedaços — uma das opções mais seguras para bebês bem pequenos.",
    howToOffer: "Segure uma ponta enquanto o bebê morde a outra.",
    goodForActiveTeething: true,
  },
  {
    id: "chupeta-gelada",
    name: "Chupeta gelada",
    emoji: "🍼",
    category: "frio",
    minAgeMonths: 0,
    temperature: "Resfriada (geladeira, não congelador)",
    prep: "Deixe a chupeta habitual do bebê na geladeira por 15-20 minutos antes de oferecer.",
    maxDurationMinutes: 15,
    safety: "Nunca congele — o silicone pode rachar e ficar cortante. Sempre geladeira, nunca freezer.",
    benefits: "Alívio frio usando um item que o bebê já conhece e aceita bem.",
    howToOffer: "Ofereça como de costume, o frio já traz o efeito extra.",
    goodForActiveTeething: true,
  },
  {
    id: "mamadeira-gelada",
    name: "Mamadeira ou copinho gelado",
    emoji: "🥤",
    category: "frio",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Sirva água bem gelada em um copinho de treino — o próprio bico frio já ajuda.",
    maxDurationMinutes: 15,
    safety: "Não ofereça líquidos congelados ou com gelo sólido — risco de engasgo.",
    benefits: "Hidrata e alivia ao mesmo tempo.",
    howToOffer: "Ofereça normalmente na rotina de líquidos do dia.",
    goodForActiveTeething: true,
  },
  {
    id: "abacaxi",
    name: "Abacaxi",
    emoji: "🍍",
    category: "extras",
    minAgeMonths: 8,
    temperature: "Gelado (geladeira)",
    prep: "Corte um bastão grosso sem casca, gelado.",
    maxDurationMinutes: 10,
    safety: "É ácido — algumas gengivas inflamadas podem ficar sensíveis. Observe a reação e pare se incomodar.",
    benefits: "As enzimas do abacaxi têm um leve efeito calmante em algumas gengivas, além do alívio pelo frio.",
    howToOffer: "Ofereça em bastão grosso, supervisionando de perto pela textura fibrosa.",
    goodForActiveTeething: true,
  },
  {
    id: "biscotto",
    name: "Biscotto (biscoito duro italiano)",
    emoji: "🍪",
    category: "extras",
    minAgeMonths: 10,
    temperature: "Ambiente",
    prep: "Escolha um biscotto simples, sem açúcar em excesso, cortado em bastão.",
    maxDurationMinutes: 10,
    safety: "É bem duro no início — só ofereça se o bebê já tiver boa força de mordida (geralmente 10+ meses).",
    benefits: "Muito resistente, demora bastante para amolecer, ótimo para sessões mais longas de mordida.",
    howToOffer: "Ofereça pela ponta, supervisionando pedaços que possam quebrar.",
    goodForActiveTeething: false,
  },
];

export const TEETHERS_ES: Teether[] = [
  {
    id: "maca",
    name: "Manzana",
    emoji: "🍎",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Frío (refrigerador)",
    prep: "Corta un bastón grueso con cáscara, enfriado en el refrigerador por 30 minutos.",
    maxDurationMinutes: 10,
    safety: "Supervisa siempre — pueden soltarse trozos con la mordida. Retíralo si queda demasiado pequeño para sostenerlo con firmeza.",
    benefits: "El frío ayuda a aliviar la inflamación de la encía; la cáscara da resistencia para morder sin romperse fácil.",
    howToOffer: "Sostén el otro extremo en los primeros usos, hasta que el bebé aprenda a sostenerlo solo.",
    goodForActiveTeething: true,
  },
  {
    id: "cenoura",
    name: "Zanahoria",
    emoji: "🥕",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Frío (refrigerador)",
    prep: "Usa un bastón entero y grueso, enfriado en el refrigerador — nunca cocida (queda demasiado blanda y se rompe).",
    maxDurationMinutes: 10,
    safety: "Usa siempre un bastón demasiado grande para caber entero en la boca. Descártalo apenas aparezcan marcas profundas de mordida.",
    benefits: "Textura firme y fría, ideal para masajear la encía.",
    howToOffer: "Ofrécela por el extremo más grueso, sosteniendo el mango con la mano.",
    goodForActiveTeething: true,
  },
  {
    id: "banana-congelada",
    name: "Banana congelada",
    emoji: "🍌",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Congelada",
    prep: "Congela media banana con cáscara por 1 a 2 horas, hasta que quede firme pero no dura como piedra.",
    maxDurationMinutes: 10,
    safety: "Se ablanda rápido — cámbiala apenas se ablande demasiado y se convierta en papilla, para evitar atragantamiento.",
    benefits: "El frío intenso es uno de los más eficaces para el alivio inmediato del dolor.",
    howToOffer: "Ofrécela con la cáscara como apoyo para la mano del bebé.",
    goodForActiveTeething: true,
  },
  {
    id: "melancia",
    name: "Sandía",
    emoji: "🍉",
    category: "frutas",
    minAgeMonths: 8,
    temperature: "Frío (refrigerador)",
    prep: "Corta un bastón grueso sin semillas, enfriado.",
    maxDurationMinutes: 10,
    safety: "Retira todas las semillas antes de ofrecerla. Queda resbaladiza — supervisa de cerca.",
    benefits: "Refrescante e hidratante, ideal en días calurosos de salida de dientes.",
    howToOffer: "Ofrécela en un trozo lo bastante grande para que no quepa entero en la boca.",
    goodForActiveTeething: true,
  },
  {
    id: "pera",
    name: "Pera",
    emoji: "🍐",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Frío (refrigerador)",
    prep: "Usa una pera firme (no muy madura), en bastón grueso, fría.",
    maxDurationMinutes: 10,
    safety: "Las peras muy maduras se ablandan rápido y se rompen — prefiere peras más firmes para este fin.",
    benefits: "Textura firme y levemente dulce, bien aceptada por la mayoría de los bebés.",
    howToOffer: "Ofrécela por el extremo, sosteniéndola junto con el bebé en los primeros usos.",
    goodForActiveTeething: true,
  },
  {
    id: "beterraba",
    name: "Remolacha",
    emoji: "🟣",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Frío (refrigerador)",
    prep: "Usa un bastón grueso crudo, frío — la textura bien firme es lo que funciona aquí.",
    maxDurationMinutes: 10,
    safety: "Puede manchar ropa y piel temporalmente (es solo el color, inofensivo). Supervisa como con cualquier mordedor de vegetal crudo.",
    benefits: "Muy firme y resistente, dura más tiempo sin romperse que otros vegetales.",
    howToOffer: "Ofrécela por el extremo más delgado, manteniendo la parte gruesa fuera de la boca.",
    goodForActiveTeething: true,
  },
  {
    id: "mordedor-silicone",
    name: "Mordedor de silicona",
    emoji: "🧸",
    category: "silicone",
    minAgeMonths: 3,
    temperature: "Ambiente o frío (apto para refrigerador)",
    prep: "Elige un mordedor de silicona de grado alimenticio (certificación FDA u homóloga local), sin BPA, de pieza única — sin partes pequeñas que puedan soltarse.",
    maxDurationMinutes: 30,
    safety: "Revisa que no tenga grietas antes de cada uso y reemplázalo al primer signo de desgaste. Nunca lo ates al cuello del bebé.",
    benefits: "Se puede enfriar en el refrigerador (nunca en el congelador, la mayoría se agrieta), reutilizable y diseñado para la seguridad.",
    howToOffer: "Lávalo después de cada uso y mantenlo limpio entre un uso y otro.",
    goodForActiveTeething: true,
  },
  {
    id: "pao",
    name: "Pan",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente o levemente tostado",
    prep: "Usa una corteza gruesa de pan tipo baguette o una rebanada de pan integral levemente tostada, en tira larga.",
    maxDurationMinutes: 10,
    safety: "Se ablanda con la saliva — cámbialo cuando empiece a deshacerse, para no correr riesgo de atragantamiento.",
    benefits: "Textura firme al principio, se va ablandando de a poco a medida que el bebé mastica.",
    howToOffer: "Ofrécelo por el extremo, dejando la otra parte fuera de la boca.",
    goodForActiveTeething: false,
  },
  {
    id: "biscoito-polvilho",
    name: "Galleta de almidón de yuca",
    emoji: "🥨",
    category: "pao",
    minAgeMonths: 8,
    temperature: "Ambiente",
    prep: "Elige una galleta de almidón de yuca simple, sin azúcar y sin relleno, en forma de argolla o bastón.",
    maxDurationMinutes: 10,
    safety: "Se ablanda y puede romperse en trozos — supervisa y retira los trozos pequeños que se suelten.",
    benefits: "Crocante al principio, práctica para llevar en el bolso.",
    howToOffer: "Ofrécela entera, sosteniéndola por el borde hasta que el bebé la agarre sola.",
    goodForActiveTeething: false,
  },
  {
    id: "torrada",
    name: "Tostada",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente",
    prep: "Tuesta una rebanada de pan integral hasta que quede bien firme y córtala en tiras largas.",
    maxDurationMinutes: 10,
    safety: "Se ablanda rápido con la saliva — cámbiala cuando quede blanda.",
    benefits: "Más firme que el pan común, dura un poco más a la mordida.",
    howToOffer: "Ofrécela en tiras largas, fáciles de sostener.",
    goodForActiveTeething: false,
  },
  {
    id: "pano-congelado",
    name: "Paño de algodón congelado",
    emoji: "🧊",
    category: "frio",
    minAgeMonths: 3,
    temperature: "Congelado",
    prep: "Moja un paño de algodón limpio en agua filtrada, escúrrelo, dóblalo y congélalo por 30-40 minutos.",
    maxDurationMinutes: 15,
    safety: "Verifica que no esté tan duro como para lastimar la encía — el paño debe ceder un poco a la presión.",
    benefits: "Alivio frío profundo, sin riesgo de que se suelten trozos — una de las opciones más seguras para bebés muy pequeños.",
    howToOffer: "Sostén un extremo mientras el bebé muerde el otro.",
    goodForActiveTeething: true,
  },
  {
    id: "chupeta-gelada",
    name: "Chupete frío",
    emoji: "🍼",
    category: "frio",
    minAgeMonths: 0,
    temperature: "Frío (refrigerador, no congelador)",
    prep: "Deja el chupete habitual del bebé en el refrigerador por 15-20 minutos antes de ofrecerlo.",
    maxDurationMinutes: 15,
    safety: "Nunca lo congeles — la silicona puede agrietarse y quedar cortante. Siempre refrigerador, nunca congelador.",
    benefits: "Alivio frío usando un objeto que el bebé ya conoce y acepta bien.",
    howToOffer: "Ofrécelo como de costumbre, el frío ya aporta el efecto extra.",
    goodForActiveTeething: true,
  },
  {
    id: "mamadeira-gelada",
    name: "Mamadera o vasito frío",
    emoji: "🥤",
    category: "frio",
    minAgeMonths: 6,
    temperature: "Frío (refrigerador)",
    prep: "Sirve agua bien fría en un vasito entrenador — el pico frío ya ayuda por sí solo.",
    maxDurationMinutes: 15,
    safety: "No ofrezcas líquidos congelados o con hielo sólido — riesgo de atragantamiento.",
    benefits: "Hidrata y alivia al mismo tiempo.",
    howToOffer: "Ofrécela normalmente en la rutina de líquidos del día.",
    goodForActiveTeething: true,
  },
  {
    id: "abacaxi",
    name: "Piña",
    emoji: "🍍",
    category: "extras",
    minAgeMonths: 8,
    temperature: "Frío (refrigerador)",
    prep: "Corta un bastón grueso sin cáscara, frío.",
    maxDurationMinutes: 10,
    safety: "Es ácida — algunas encías inflamadas pueden quedar sensibles. Observa la reacción y detente si molesta.",
    benefits: "Las enzimas de la piña tienen un leve efecto calmante en algunas encías, además del alivio por el frío.",
    howToOffer: "Ofrécela en bastón grueso, supervisando de cerca por su textura fibrosa.",
    goodForActiveTeething: true,
  },
  {
    id: "biscotto",
    name: "Biscotto (galleta dura italiana)",
    emoji: "🍪",
    category: "extras",
    minAgeMonths: 10,
    temperature: "Ambiente",
    prep: "Elige un biscotto simple, sin exceso de azúcar, cortado en bastón.",
    maxDurationMinutes: 10,
    safety: "Es bastante duro al principio — ofrécelo solo si el bebé ya tiene buena fuerza de mordida (generalmente 10+ meses).",
    benefits: "Muy resistente, tarda bastante en ablandarse, ideal para sesiones más largas de mordida.",
    howToOffer: "Ofrécelo por el extremo, supervisando los trozos que puedan romperse.",
    goodForActiveTeething: false,
  },
];

export function getTeethers(locale: Locale = "pt-BR"): Teether[] {
  return locale === "es" ? TEETHERS_ES : TEETHERS;
}

export const TEETHING_NORMAL_SIGNS: string[] = [
  "Salivação bem acima do normal",
  "Gengiva inchada ou avermelhada em um ponto específico",
  "Vontade de morder tudo que encontra pela frente",
  "Irritabilidade, principalmente à noite",
  "Leve aumento da temperatura (sem chegar a febre)",
  "Sono mais agitado que o habitual",
  "Recusa parcial de alimentos por desconforto na boca",
];

export const TEETHING_NORMAL_SIGNS_ES: string[] = [
  "Salivación muy por encima de lo normal",
  "Encía hinchada o enrojecida en un punto específico",
  "Ganas de morder todo lo que encuentra por delante",
  "Irritabilidad, especialmente por la noche",
  "Leve aumento de la temperatura (sin llegar a fiebre)",
  "Sueño más agitado de lo habitual",
  "Rechazo parcial de alimentos por molestia en la boca",
];

export function getTeethingNormalSigns(locale: Locale = "pt-BR"): string[] {
  return locale === "es" ? TEETHING_NORMAL_SIGNS_ES : TEETHING_NORMAL_SIGNS;
}

export const TEETHING_WARNING_SIGNS: string[] = [
  "Febre alta (acima de 38°C) — teething não causa febre alta, procure o pediatra.",
  "Diarreia ou vômitos — também não são causados por teething, investigue outra causa.",
  "Feridas abertas, sangramento ou pus na gengiva — pare de usar mordedores e procure avaliação.",
];

export const TEETHING_WARNING_SIGNS_ES: string[] = [
  "Fiebre alta (por encima de 38 °C) — la salida de dientes no causa fiebre alta, consulta al pediatra.",
  "Diarrea o vómitos — tampoco son causados por la salida de dientes, investiga otra causa.",
  "Heridas abiertas, sangrado o pus en la encía — deja de usar mordedores y busca una evaluación.",
];

export function getTeethingWarningSigns(locale: Locale = "pt-BR"): string[] {
  return locale === "es" ? TEETHING_WARNING_SIGNS_ES : TEETHING_WARNING_SIGNS;
}

export function teethersForActiveTeething(locale: Locale = "pt-BR"): Teether[] {
  return getTeethers(locale).filter((t) => t.goodForActiveTeething);
}
