export type TeetherCategory = "frutas" | "silicone" | "pao" | "frio" | "extras";

export const TEETHER_CATEGORY_LABEL: Record<TeetherCategory, string> = {
  frutas: "Frutas",
  silicone: "Silicone",
  pao: "Pão & biscoito",
  frio: "Frio",
  extras: "Extras",
};

export interface Teether {
  id: string;
  name: string;
  emoji: string;
  category: TeetherCategory;
  minAgeMonths: number;
  temperature: string;
  prep: string;
  maxDurationMinutes: number;
  safety: string;
  benefits: string;
  howToOffer: string;
  goodForActiveTeething: boolean;
}

export const TEETHERS: Teether[] = [
  {
    id: "maca",
    name: "Maçã",
    emoji: "🍎",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Corte um bastão grosso com casca, gelado na geladeira por 30 minutos.",
    maxDurationMinutes: 10,
    safety: "Supervisione sempre — pedaços podem se soltar com a mordida. Retire se ficar pequeno demais para segurar com firmeza.",
    benefits: "O frio ajuda a aliviar a inflamação da gengiva; a casca dá resistência para morder sem quebrar fácil.",
    howToOffer: "Segure a outra ponta nos primeiros usos, até o bebê pegar o jeito de segurar sozinho.",
    goodForActiveTeething: true,
  },
  {
    id: "cenoura",
    name: "Cenoura",
    emoji: "🥕",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use um bastão inteiro e grosso, gelado na geladeira — nunca cozida (fica mole demais e quebra).",
    maxDurationMinutes: 10,
    safety: "Use sempre um bastão grande demais para caber inteiro na boca. Descarte assim que aparecerem marcas fundas de mordida.",
    benefits: "Textura firme e fria, ótima para massagear a gengiva.",
    howToOffer: "Ofereça pela ponta mais grossa, seguindo o cabo com a mão.",
    goodForActiveTeething: true,
  },
  {
    id: "banana-congelada",
    name: "Banana congelada",
    emoji: "🍌",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Congelada",
    prep: "Congele meia banana com casca por 1 a 2 horas, até ficar firme mas não pedra.",
    maxDurationMinutes: 10,
    safety: "Fica mole rápido — troque assim que amolecer demais e vire papinha, para evitar sufoco.",
    benefits: "O frio intenso é um dos mais eficazes para alívio imediato da dor.",
    howToOffer: "Ofereça com a casca como apoio para a mão do bebê.",
    goodForActiveTeething: true,
  },
  {
    id: "melancia",
    name: "Melancia",
    emoji: "🍉",
    category: "frutas",
    minAgeMonths: 8,
    temperature: "Gelada (geladeira)",
    prep: "Corte um bastão grosso sem sementes, gelado.",
    maxDurationMinutes: 10,
    safety: "Retire todas as sementes antes de oferecer. Fica escorregadia — supervisione de perto.",
    benefits: "Refrescante e hidratante, ótima em dias quentes de teething.",
    howToOffer: "Ofereça em pedaço grande o suficiente para não caber inteiro na boca.",
    goodForActiveTeething: true,
  },
  {
    id: "pera",
    name: "Pera",
    emoji: "🍐",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use uma pera firme (não muito madura), em bastão grosso, gelada.",
    maxDurationMinutes: 10,
    safety: "Peras muito maduras amolecem rápido e quebram — prefira peras mais firmes para essa finalidade.",
    benefits: "Textura firme e levemente doce, bem aceita pela maioria dos bebês.",
    howToOffer: "Ofereça pela ponta, segurando junto nos primeiros usos.",
    goodForActiveTeething: true,
  },
  {
    id: "beterraba",
    name: "Beterraba",
    emoji: "🟣",
    category: "frutas",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Use um bastão grosso cru, gelado — a textura bem firme é o que funciona aqui.",
    maxDurationMinutes: 10,
    safety: "Pode manchar roupas e pele temporariamente (é só a cor, inofensivo). Supervisione como qualquer mordedor de vegetal cru.",
    benefits: "Muito firme e resistente, dura mais tempo sem quebrar do que outros vegetais.",
    howToOffer: "Ofereça pela ponta mais fina, mantendo a parte grossa fora da boca.",
    goodForActiveTeething: true,
  },
  {
    id: "mordedor-silicone",
    name: "Mordedor de silicone",
    emoji: "🧸",
    category: "silicone",
    minAgeMonths: 3,
    temperature: "Ambiente ou gelado (próprio para geladeira)",
    prep: "Escolha um mordedor de silicone alimentício (grade INMETRO/FDA), sem BPA, com peça única — sem partes pequenas que possam soltar.",
    maxDurationMinutes: 30,
    safety: "Verifique rachaduras antes de cada uso e substitua ao primeiro sinal de desgaste. Nunca amarre no pescoço do bebê.",
    benefits: "Pode ser gelado na geladeira (nunca no freezer, a maioria racha), reutilizável e desenhado para segurança.",
    howToOffer: "Lave após cada uso e mantenha limpo entre uma oferta e outra.",
    goodForActiveTeething: true,
  },
  {
    id: "pao",
    name: "Pão",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente ou levemente torrado",
    prep: "Use uma casca grossa de pão francês ou uma fatia de pão integral levemente torrada, em tira comprida.",
    maxDurationMinutes: 10,
    safety: "Fica mole com a saliva — troque quando começar a desmanchar, para não virar risco de engasgo.",
    benefits: "Textura firme no início, vai amolecendo aos poucos conforme o bebê mastiga.",
    howToOffer: "Ofereça pela ponta, deixando a outra parte de fora da boca.",
    goodForActiveTeething: false,
  },
  {
    id: "biscoito-polvilho",
    name: "Biscoito de polvilho",
    emoji: "🥨",
    category: "pao",
    minAgeMonths: 8,
    temperature: "Ambiente",
    prep: "Escolha um biscoito de polvilho simples, sem açúcar e sem recheio, em formato de argola ou bastão.",
    maxDurationMinutes: 10,
    safety: "Amolece e pode quebrar em pedaços — supervisione e retire pedaços pequenos que se soltarem.",
    benefits: "Crocante no início, prático para levar na bolsa.",
    howToOffer: "Ofereça inteiro, segurando pela borda até o bebê pegar sozinho.",
    goodForActiveTeething: false,
  },
  {
    id: "torrada",
    name: "Torrada",
    emoji: "🍞",
    category: "pao",
    minAgeMonths: 6,
    temperature: "Ambiente",
    prep: "Torre uma fatia de pão integral até ficar bem firme e corte em tiras compridas.",
    maxDurationMinutes: 10,
    safety: "Amolece rápido com a saliva — troque quando ficar mole.",
    benefits: "Mais firme que o pão comum, dura um pouco mais na mordida.",
    howToOffer: "Ofereça em tiras compridas, fáceis de segurar.",
    goodForActiveTeething: false,
  },
  {
    id: "pano-congelado",
    name: "Pano de algodão congelado",
    emoji: "🧊",
    category: "frio",
    minAgeMonths: 3,
    temperature: "Congelado",
    prep: "Molhe um pano de algodão limpo em água filtrada, torça, dobre e congele por 30-40 minutos.",
    maxDurationMinutes: 15,
    safety: "Verifique que não está tão duro a ponto de machucar a gengiva — o pano deve ceder um pouco à pressão.",
    benefits: "Alívio frio profundo, sem risco de soltar pedaços — uma das opções mais seguras para bebês bem pequenos.",
    howToOffer: "Segure uma ponta enquanto o bebê morde a outra.",
    goodForActiveTeething: true,
  },
  {
    id: "chupeta-gelada",
    name: "Chupeta gelada",
    emoji: "🍼",
    category: "frio",
    minAgeMonths: 0,
    temperature: "Resfriada (geladeira, não congelador)",
    prep: "Deixe a chupeta habitual do bebê na geladeira por 15-20 minutos antes de oferecer.",
    maxDurationMinutes: 15,
    safety: "Nunca congele — o silicone pode rachar e ficar cortante. Sempre geladeira, nunca freezer.",
    benefits: "Alívio frio usando um item que o bebê já conhece e aceita bem.",
    howToOffer: "Ofereça como de costume, o frio já traz o efeito extra.",
    goodForActiveTeething: true,
  },
  {
    id: "mamadeira-gelada",
    name: "Mamadeira ou copinho gelado",
    emoji: "🥤",
    category: "frio",
    minAgeMonths: 6,
    temperature: "Gelada (geladeira)",
    prep: "Sirva água bem gelada em um copinho de treino — o próprio bico frio já ajuda.",
    maxDurationMinutes: 15,
    safety: "Não ofereça líquidos congelados ou com gelo sólido — risco de engasgo.",
    benefits: "Hidrata e alivia ao mesmo tempo.",
    howToOffer: "Ofereça normalmente na rotina de líquidos do dia.",
    goodForActiveTeething: true,
  },
  {
    id: "abacaxi",
    name: "Abacaxi",
    emoji: "🍍",
    category: "extras",
    minAgeMonths: 8,
    temperature: "Gelado (geladeira)",
    prep: "Corte um bastão grosso sem casca, gelado.",
    maxDurationMinutes: 10,
    safety: "É ácido — algumas gengivas inflamadas podem ficar sensíveis. Observe a reação e pare se incomodar.",
    benefits: "As enzimas do abacaxi têm um leve efeito calmante em algumas gengivas, além do alívio pelo frio.",
    howToOffer: "Ofereça em bastão grosso, supervisionando de perto pela textura fibrosa.",
    goodForActiveTeething: true,
  },
  {
    id: "biscotto",
    name: "Biscotto (biscoito duro italiano)",
    emoji: "🍪",
    category: "extras",
    minAgeMonths: 10,
    temperature: "Ambiente",
    prep: "Escolha um biscotto simples, sem açúcar em excesso, cortado em bastão.",
    maxDurationMinutes: 10,
    safety: "É bem duro no início — só ofereça se o bebê já tiver boa força de mordida (geralmente 10+ meses).",
    benefits: "Muito resistente, demora bastante para amolecer, ótimo para sessões mais longas de mordida.",
    howToOffer: "Ofereça pela ponta, supervisionando pedaços que possam quebrar.",
    goodForActiveTeething: false,
  },
];

export const TEETHING_NORMAL_SIGNS: string[] = [
  "Salivação bem acima do normal",
  "Gengiva inchada ou avermelhada em um ponto específico",
  "Vontade de morder tudo que encontra pela frente",
  "Irritabilidade, principalmente à noite",
  "Leve aumento da temperatura (sem chegar a febre)",
  "Sono mais agitado que o habitual",
  "Recusa parcial de alimentos por desconforto na boca",
];

export const TEETHING_WARNING_SIGNS: string[] = [
  "Febre alta (acima de 38°C) — teething não causa febre alta, procure o pediatra.",
  "Diarreia ou vômitos — também não são causados por teething, investigue outra causa.",
  "Feridas abertas, sangramento ou pus na gengiva — pare de usar mordedores e procure avaliação.",
];

export function teethersForActiveTeething(): Teether[] {
  return TEETHERS.filter((t) => t.goodForActiveTeething);
}
